from aiogram.fsm.state import State, StatesGroup


class UserStates(StatesGroup):
    ask_support_photo = State()
    registration_enter_city = State()
    registration_end = State()
    menu = State()
    ask_support = State()
    user_info = State()


class WorkStates(StatesGroup):
    portfolio_upload_photo = State()
    create_name_profile = State()
    create_photo_profile = State()
    individual_entrepreneur = State()
    registration_enter_city = State()
    # Верификация убрана согласно ТЗ
    worker_menu = State()
    worker_check_subscription = State()
    worker_buy_subscription = State()
    worker_choose_work_types = State()
    worker_apply_order = State()
    worker_check_abs = State()
    worker_change_city = State()
    worker_responses = State()
    create_portfolio = State()
    # Новые состояния для системы покупки контактов
    worker_buy_contacts = State()
    worker_contact_purchase = State()


class CustomerStates(StatesGroup):
    customer_extend_abc = State()
    enter_phone_number = State()
    # customer_buy_subscription = State()  # Убрано - размещение всегда бесплатно
    registration_enter_city = State()
    # Верификация убрана согласно ТЗ
    customer_menu = State()
    worker_check_abs = State()
    customer_create_abs = State()
    customer_create_abs_work_type = State()
    customer_choose_work_sub_types = State()
    customer_create_abs_task = State()
    customer_create_abs_volume = State()
    customer_create_abs_details = State()
    customer_create_abs_address = State()
    customer_create_abs_price = State()
    customer_create_abs_choose_time = State()
    customer_create_abs_add_photo = State()
    customer_check_abs = State()
    customer_apply_worker = State()
    customer_apply_worker_send_msg = State()
    send_contact_to_worker = State()
    starring_worker = State()
    customer_change_city = State()
    customer_apply_worker_text = State()
    customer_response = State()
    customer_response_apply_worker = State()
    response_send_contact_to_worker = State()
    customer_response_apply_worker_text = State()
    customer_create_abs_personal_add_photo =State()
    # Новые состояния для системы покупки контактов
    customer_send_contacts = State()


class AdminStates(StatesGroup):
    add_comment_to_lock_profile_photo = State()
    edit_stop_words_short_photo_delite = State()
    edit_stop_words_short_photo_insert = State()
    edit_stop_words_short_photo = State()
    edit_photo_stop_words_delite = State()
    edit_photo_stop_words_insert = State()
    edit_photo_stop_words = State()
    edit_stop_words_short_personal_delite = State()
    edit_stop_words_short_personal_insert = State()
    edit_stop_words_short_personal = State()
    edit_personal_stop_words_delite = State()
    edit_personal_stop_words_insert = State()
    edit_personal_stop_words = State()
    edit_stop_words_short_message_insert = State()
    edit_stop_words_long_message_insert = State()
    edit_stop_words_short_message_delite = State()
    edit_stop_words_short_message = State()
    edit_stop_words_long_message = State()
    edit_stop_words_long_message_delite = State()
    send_to_user = State()
    get_user = State()
    get_worker = State()
    get_customer = State()
    menu = State()
    msg_to_worker_text = State()
    msg_to_worker_photo = State()
    msg_to_customer_text = State()
    msg_to_customer_photo = State()
    msg_to_all_text = State()
    msg_to_all_photo = State()
    msg_to_worker_choose_city = State()
    msg_to_worker_text_city = State()
    msg_to_worker_photo_city = State()
    msg_to_customer_text_city = State()
    msg_to_customer_choose_city = State()
    msg_to_customer_photo_city = State()
    msg_to_all_choose_city = State()
    msg_to_all_text_city = State()
    msg_to_all_photo_city = State()
    add_account = State()
    account_role = State()
    enter_rework = State()
    edit_stop_words = State()
    edit_stop_words_long = State()
    edit_stop_words_short = State()
    edit_white_words = State()
    edit_stop_words_profanity = State()
    edit_stop_words_long_insert = State()
    edit_stop_words_short_insert = State()
    edit_white_words_insert = State()
    edit_stop_words_profanity_insert = State()
    edit_stop_words_long_delite = State()
    edit_stop_words_short_delite = State()
    edit_white_words_delite = State()
    edit_stop_words_profanity_delite = State()
    edit_stop_words_long_look = State()
    edit_stop_words_short_look = State()
    edit_white_words_look = State()
    edit_stop_words_profanity_look = State()
    admin_answer_user = State()
    unblock_user = State()
    block_user = State()
    check_subscription = State()
    edit_subscription = State()
    msg_to_worker_choose_city_ref = State()
    msg_to_worker_text_city_ref = State()
    msg_to_worker_photo_city_ref = State()
    msg_to_worker_ref = State()
    msg_to_worker_text_ref = State()
    msg_to_worker_photo_ref = State()
    edit_subscription_price = State()
    edit_subscription_order = State()
    check_abs = State()
    check_banned_abs = State()
    add_comment_to_lock = State()
    add_comment_to_lock_abs_chat = State()


class BannedStates(StatesGroup):
    banned = State()


#  _    _        _      _____              _
# | |  | |      | |    |_   _|            | |
# | |  | |  ___ | |__    | |    ___   ___ | |__
# | |/\| | / _ \| '_ \   | |   / _ \ / __|| '_ \
# \  /\  /|  __/| |_) |  | |  |  __/| (__ | | | |
#  \/  \/  \___||_.__/   \_/   \___| \___||_| |_|
